.\" (C) Copyright 2014 arnault perret <arpinux@member.fsf.org>,
.TH REDSHIFT-CONFIG 1 "March 29, 2014"
.SH NAME
redshift-config \- automatic configration tool for gtk-redshift
.SH SYNOPSIS
.B redshift-config
.SH DESCRIPTION
redshift-config allow you to configure your location to be used with gtk-redshift,
the screen filter. Simply launch
.B redshift-config 
to configure, launch, refresh or stop redshift screen filter.
redshift-config needs an active network connection.
.PP
.TH redshift-config-en_0.7
