.\" (C) Copyright 2014 arnault perret <arpinux@member.fsf.org>,
.TH MPARTAGE 1 "March 29, 2014"
.SH NAME
mpartage \- partagez facilement vos données
.SH SYNOPSIS
.B mpartage
.SH DESCRIPTION
m_partage est un outil graphique de partage de données.
Lancez simplement
.B m_partage
et glissez-déposez le dossier que vous désirez partager.
deux adresses internet s'affichent : la première pour le
partage local, la seconde pour le partage distant.
Transmettez ces liens à votre correspondant.
Le partage s'arrête quand vous fermez
.B mpartage
ou quand vous décochez l'activation du partage.
.PP
.TH m_partage
