.\" (C) Copyright 2015 arnault perret <arpinux@member.fsf.org>,
.TH BTSHARE-HWEB 1 "May  1, 2015"
.SH NAME
btshare-hweb \- partagez vos données via P2P
.SH SYNOPSIS
.B btshare-web
.RI " dossier à partager" ...
.br
.SH DESCRIPTION
Ce manuel décrit brièvement le fonctionnement de 
.B btshare-web
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
.SH BTSHARE-WEB
btshare-web by thuban vous permet de partager facilement des données 
via BitTorrent depuis une interface web simplifiée. 
Plus d'informations dans /usr/share/btshare/README.md
