.\" (C) Copyright 2014 arnault perret <arpinux@member.fsf.org>,
.TH REDSHIFT-CONFIG 1 "March 29, 2014"
.SH NAME
redshift-config \- configuration automatique du filtre redshift
.SH SYNOPSIS
.B redshift-config
.SH DESCRIPTION
redshift-config est un outil graphique pour le filtre d'écran redshift.
Lancez simplement
.B redshift-config 
pour configurer, lancer ou désactiver le filtre d'écran redshift.
La configuration a besoin d'un connexion internet active.
.PP
.TH redshift-config_0.7
