.
.TH ldmconf 18 "January 2016" "" "Configure lightDM"
.SH NAME
ldmconf \- Login configuration
.
.SH SYNOPSIS
.RS
ldmconf :

    * ldmconf vous permet de configurer votre écran de connexion. 
.RE

.SH DESCRIPTION
.RS
Avec ldmconf, vous pouvez configurer : 
    * La connexion automatique pour un utilisateur
    * Changer le fond d'écran à la connexion
    * Modifier l'apparence de l'écran de connexion : police, thème GTK et thème d'icônes.
.RE

.SH BUGS
.RS
C'est de la faute à : <thuban@yeuxdelibad.net>
.RE

