.\" (C) Copyright 2014 arnault perret <arpinux@member.fsf.org>,
.TH HANDY-MENU 1 "March 29, 2014"
.SH NAME
handy-menu \- menu principal d'HandyLinux
.SH SYNOPSIS
.B handy-menu
.SH DESCRIPTION
Le HandyMenu est un menu graphique simplifié intégrant son outil de configuration. 
Lancez simplement
.B handymenu.
.SH CONFIGURATION
Le HandyMenu est configurable graphiquement depuis le bouton préférences, depuis un clic-droit sur un des boutons du menu, ou depuis son fichier de configuration $HOME/.handymenu.conf
.PP
.TH handy-menu_2.0
