.TH HANDYMENU 1 "June 4, 2015"
.SH NAME
handymenu \- menu principal d'HandyLinux
.SH SYNOPSIS
.B handymenu
.SH DESCRIPTION
Le HandyMenu est un menu graphique simplifié intégrant son outil de configuration. 
Lancez simplement
.B handymenu.
.SH CONFIGURATION
Le HandyMenu est configurable graphiquement depuis le bouton préférences.
.PP
