.\" (C) Copyright 2014 arnault perret <arpinux@member.fsf.org>,
.TH HANDY2DEBIAN 1 "March 29, 2014"
.SH NAME
handy2debian \- passer à Debian en un clic
.SH SYNOPSIS
.B handy2debian
.SH DESCRIPTION
Handy2Debian est un outil graphique simplifié pour éliminer handylinux et passer à Debian "classic". 
Lancez simplement
.B handy2debian.
.PP
.TH handy2debian_0.1
