.TH LOUPY 1 "July 31, 2015"
.SH NAME
loupy \- une loupe passive
.SH DESCRIPTION
.B loupy
est une loupe passive (qui ne clique pas) en python ultra-légère
.
.br
le clic gauche cache la loupe, qui reste accessible dans la zone de notification.
.br
le clic-gauche dépose la loupe, un second clic-gauche vous permet de reprendre la main.
.br
la molette et les touches + et - augmentent ou réduisent le zoom.
.br
vous pouvez aussi utiliser les flèches du clavier pour piloter loupy.
.br
la touche r recharge la loupe et la touche Échap (Esc) stoppe loupy.
.br
