#!/bin/bash
# simple teamviewer installer for Debian by coyotus
# modified by thuban

# à changer en cas de màj
DEBURL="https://handylinux.org/stock_files/nonfree/teamviewer-latest.deb"

if [ `whoami` != root ]
	then
	    gksu -D "Teamviewer install" $0
	exit 1
fi

DLTEAMVW="# Downloading TeamViewer."
PREPSYS="# Preparing the system: install dependancies."
ADDARCH="# Adding i386 architecture"
INSTALLINFO="# Teamviewer installation.\n\nA message will be displayed at the end of the process."
ADDARCH="Adding i386 architecture"
EXECDPKG="# Package manager running \n\ndpkg -i teamviewer_i386.deb"
DELDEB="# Removing installer"
DELINSTALLER="# Removing the installation script."
OK="# TeamViewer is installed.\n\nYou can launch it from the Applications list."
ERROR="# Oops ... something gets wrong..."

case $LANG in
	fr*)
        DLTEAMVW="# Téléchargement de TeamViewer."
        PREPSYS="# Préparation du système : installation des dépendances."
        ADDARCH="# Ajout de l'architecture i386."
        INSTALLINFO="# Installation de Teamviewer.\n\nUn message vous informera en fin d'installation." 
        ADDARCH="Ajout de l'architecture i386"
        EXECDPKG="# Execution du gestionnaire de paquet !\n\ndpkg -i teamviewer_i386.deb"
        DELDEB="# Suppression de l'installeur !\n\nrm teamviewer_i386.deb"
        DELINSTALLER="# Suppression du script d'installation."
        OK="# TeamViewer est installé.\n\nVous pouvez le lancer depuis la liste des Applications."
        ERROR="# Oups ... une erreur s'est produite..."
        ;;
esac

exec &> >(tee -a -) # avoir du debug dans le terminal
set -x #verbose

(
    echo "$DLTEAMVW"
    echo "0"
    rm -rf teamviewer_i386.deb # pour etre sûr qu il renomme pas en .deb.1
    wget -O teamviewer_i386.deb "$DEBURL" 2>&1 |\
        sed -u "s/^[a-zA-Z\-].*//; s/.* \{1,2\}\([0-9]\{1,3\}\)%.*/\1\n${DLTEAMVW}..   \1%/"
) | \
zenity --progress \
    --percentage=0 \
    --title="Teamviewer Installer" \
    --auto-close \
    --auto-kill

if [[ ${PIPESTATUS[0]} -ne 0 ]]; then # en cas d'échec du DL
    zenity --error --text="$ERROR"
    exit 1
fi

(
    # Architecture i386 à ajouter
    if [ "$(uname -m)" == "x86_64" ]; then
        if [ "$(dpkg --print-foreign-architectures)" != "i386" ]; then
            echo "$ADDARCH"
            dpkg --add-architecture i386
            apt-get update
        fi
    fi

    echo "$PREPSYS"
    apt-get update
    apt-get upgrade -y
    apt-get --yes --force-yes install pulseaudio pavucontrol

    # installation de teamviewer
    echo "$INSTALLINFO" ; sleep 2
    echo "$EXECDPKG" ; dpkg -i teamviewer_i386.deb
    apt-get install --yes --force-yes -f
    echo "$DELDEB" ; rm teamviewer_i386.deb
    if [ -e /usr/bin/teamviewer ]; then
        echo "$DELINSTALLER"
        rm /usr/share/applications/teamviewer-installer.desktop
        echo "$OK" ; sleep 2
    else
        echo "$ERROR" ; sleep 2
    fi
) |

zenity --progress \
    --pulsate \
    --title="Teamviewer Installer" \
    --auto-kill 

(( $? != 0 )) && zenity --error --text="$ERROR"

set +x #plus de verbose
exit 0
