.TH CYCLOPE 1 "Sept, 08 2015"
.SH NAME
cyclope \- une visionneuse d'images par thuban
.SH DESCRIPTION
.B cyclope
est une visionneuse d'image en python ultra-légère
.br
.SH USAGE
utiliser les flèches ou les touches b et n pour faire défiler les images
.br
utiliser la touche o pour ouvrir une image
.br
utiliser la touche p pour lancer ou stopper le diaporama
.br
utiliser la touche m ou le clic-droit pour afficher le menu
.br
utiliser la touche f ou le double-clic pour dés/activer le plein-écran.
.br
utiliser les touches d ou g pour faire pivoter l'image
.br
utiliser la touche z pour passer en mode zoom : sélectionner alors une zone avec votre curseur, le zoom sera lancé une fois le clic laché.
.br
utiliser la touche = pour quitter le mode zoom
.br
maintenir le clic-gauche pour déplacer la fenêtre
.br
utiliser ESC ou q pour quitter.
.br
.TH cyclope
