.TH HANDY-UPDATE-NOTIFIER 1 "January 11, 2016"
.SH NAME
handy-update-notifier \- outil de notification des mises à jour disponibles
.SH SYNOPSIS
.B handy-update-notifier
.SH DESCRIPTION
Le Handy-update-notifier affiche le nombre de mises à jour disponibles.
.SH UTILISATION
Lancez simplement
.B handy-update-notifier
.PP
