.TH HANDY-UPGRADE-MANAGER 1 "January 11, 2016"
.SH NAME
handy-upgrade-manager \- outil de mise à jour système
.SH SYNOPSIS
.B handy-upgrade-manager
.SH DESCRIPTION
Le Handy-upgrade-manager est un outil simplifié pour mettre à jour votre système.
.SH UTILISATION
Lancez simplement
.B handy-upgrade-manager
.PP
