.TH HANDY-UPDATE-CHECKER 1 "January 11, 2016"
.SH NAME
handy-update-checker \- outil de vérification des mises à jour disponibles
.SH SYNOPSIS
.B handy-update-checker
.SH DESCRIPTION
Le Handy-update-checker vous permet de vérifier simplement les mises à jour disponibles pour votre système.
.SH UTILISATION
Lancez simplement
.B handy-update-checker
.PP
