#!/usr/bin/python 
# -*- coding:Utf-8 -*- 

"""
myHandyLinux :
	description de la handylinux installée
	HandyLinux <https://handylinux.org>

Auteurs :
        thuban (thuban@yeuxdelibad.net)  
        coyotus (http://coyotus.com)

licence :       GNU General Public Licence v3
Dépendances :   python-gtk2, python-apt
"""

import os
import pygtk
pygtk.require('2.0')
import gtk
import apt_pkg

blue  = '\033[34m'
handyicon = "/usr/share/pixmaps/handymenu_icon.png"

general = """ basée sur <a href='https://www.debian.org/' >Debian stable</a>
 homepage : <a href='https://handylinux.org' >https://handylinux.org</a>
 documentation : <a href='https://handylinux.org/wiki' >https://handylinux.org/wiki</a>
 contact : <a href='contact@handylinux.org' >contact@handylinux.org</a>
"""

authors = """ guantas -- grand initiateur
 <a href='http://yeuxdelibad.net'>thuban</a> &amp; Starsheep -- admin &amp; dev
 fibi -- zebulon'man -- <a href='http://blog.handylinux.org' >blog</a> et tests
 <a href='http://www.salem-saberhagen.cat/' >wiscot</a> -- admin de l'ombre
 <a href='http://coyotus.com' >coyotus</a> -- dev@tout'heure
 bruno-legrand -- <a href='http://emmabuntus.sourceforge.net/blog/' >EmmaSpy</a>
 Tiberias81 -- design(é)<a href='https://handylinux.org/start' >graphisme</a>
 Trefix -- modé(t)ra(c)teur
 Rouzigalos -- wiki'œil de lynx'
 <a href='http://www.dypelec.com/fr/informatique/' >dyp</a> -- MyticModo
 <a href='http://arpinux.org' >arpinux</a> -- packager
 + Toute l'équipe Debian
"""

handytools = ["handymenu", "handy-menu", "handysoft", "handytri", "handylinuxlook", "redshift-config", "mpartage", "btshare-hweb", "loupy", "cyclope"]

class MyHandylinux():
    def close_application(self, widget, event, data=None):
        gtk.main_quit()
        return False

    def get_pkg_version(self,pkgname, cache):
        try:
            pkg = cache[pkgname]
            if pkg.current_state == apt_pkg.CURSTATE_INSTALLED:
                return(pkg.current_ver.ver_str)
            else:
                return("")
        except KeyError:
            return("")

    def handytools_version(self):
        apt_pkg.init()
        cache = apt_pkg.Cache()
        for tool in handytools:
            version = self.get_pkg_version(tool, cache)
            if version:
                self.htools += "{} : {}\n               ".format(tool,version)

    def build_gui(self):
        # interface graphique
        mainbox = gtk.VBox(False, 2)
        
        # titre
        titlelbl = gtk.Label("HANDYLINUX © 2013-2016 <a href='http://www.gnu.org/licenses/gpl.txt' >GPLv3</a>".format(general))
        titlelbl.set_use_markup(True)

        # logo
        logo = gtk.Image()
        pixbuf = gtk.gdk.pixbuf_new_from_file(handyicon)
        scaled_buf = pixbuf.scale_simple(64,64,gtk.gdk.INTERP_BILINEAR)
        logo.set_from_pixbuf(scaled_buf)

        # info HL
        hltoolslbl = gtk.Label(general)
        hltoolslbl.set_use_markup(True)
        hltoolslbl.set_alignment(-0.9,0)

        # info sur l'ordinateur
        infolabel = gtk.Label("<span color=\"blue\">Mon HandyLinux</span>\n\
 Install : {}\n\
 Version : {}\n\
 Outils : {}".format(self.handyinst,self.handyvs, self.htools))
        infolabel.set_use_markup(True)
        infolabel.set_alignment(-0.9,0)

        # auteurs de HL
        authorslbl = gtk.Label("<span color=\"blue\">L'équipe</span>\n{}".format(authors))
        authorslbl.set_use_markup(True)
        authorslbl.set_alignment(-0.9,0)

        # bouton contributions
        contribbtn = gtk.LinkButton(uri = "https://handylinux.org/wiki/doku.php/fr/contribution", label = "Participer")

        # on met tout en place
        mainbox.pack_start(titlelbl, True, True, 0)
        mainbox.pack_start(logo, True, True, 0)
        mainbox.pack_start(hltoolslbl, True, True, 0)
        mainbox.pack_start(infolabel, True, True, 0)
        mainbox.pack_start(authorslbl, True, True, 10)
        mainbox.pack_start(contribbtn, True, True, 0)

        self.window = gtk.Window(gtk.WINDOW_TOPLEVEL)
        self.window.connect("delete_event", self.close_application)
        self.window.set_title("About Handylinux")
        self.window.set_border_width(10)
        self.window.set_icon_from_file(handyicon)
        self.window.set_position(gtk.WIN_POS_CENTER)

        self.window.add(mainbox)
        self.window.show_all()

    def __init__(self):
        self.htools = ""

        if os.path.isfile('/etc/handylinux_installation'):
            with open('/etc/handylinux_installation', 'r') as hi:
                self.handyinst = hi.read().strip()
        else:
            self.handyinst = " ante HandyLinux-1.5.1"
        with open('/etc/handylinux_version', 'r') as hv:
            self.handyvs = hv.read().strip()

        self.handytools_version()

        self.build_gui()

def main():
    info = MyHandylinux()
    gtk.main()
    return 0        

if __name__ == "__main__":
    main()

# vim: tabstop=4 expandtab shiftwidth=4 softtabstop=4
